/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedChequesRouteImport } from './routes/_authenticated/cheques'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNewBillRouteImport } from './routes/_authenticated/new-bill'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedAccountsAccountIdRouteImport } from './routes/_authenticated/accounts.$accountId'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills.index'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills.$billId'
import { Route as AuthenticatedCashBankIndexRouteImport } from './routes/_authenticated/cash-bank.index'
import { Route as AuthenticatedCreditNotesIndexRouteImport } from './routes/_authenticated/credit-notes.index'
import { Route as AuthenticatedCreditNotesCreditNoteIdRouteImport } from './routes/_authenticated/credit-notes.$creditNoteId'
import { Route as AuthenticatedCreditNotesNewRouteImport } from './routes/_authenticated/credit-notes.new'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedDeliveryNotesIndexRouteImport } from './routes/_authenticated/delivery-notes.index'
import { Route as AuthenticatedDeliveryNotesDeliveryIdRouteImport } from './routes/_authenticated/delivery-notes.$deliveryId'
import { Route as AuthenticatedDeliveryNotesNewRouteImport } from './routes/_authenticated/delivery-notes.new'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedPurchaseBillsIndexRouteImport } from './routes/_authenticated/purchase-bills.index'
import { Route as AuthenticatedPurchaseBillsPurchaseBillIdRouteImport } from './routes/_authenticated/purchase-bills.$purchaseBillId'
import { Route as AuthenticatedPurchaseBillsNewRouteImport } from './routes/_authenticated/purchase-bills.new'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase-orders.index'
import { Route as AuthenticatedPurchaseOrdersOrderIdRouteImport } from './routes/_authenticated/purchase-orders.$orderId'
import { Route as AuthenticatedPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchase-orders.new'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsDayBookRouteImport } from './routes/_authenticated/reports.day-book'
import { Route as AuthenticatedReportsPurchasesRouteImport } from './routes/_authenticated/reports.purchases'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated/reports.sales'
import { Route as AuthenticatedReportsTransactionsRouteImport } from './routes/_authenticated/reports.transactions'
import { Route as AuthenticatedSalesOrdersIndexRouteImport } from './routes/_authenticated/sales-orders.index'
import { Route as AuthenticatedSalesOrdersOrderIdRouteImport } from './routes/_authenticated/sales-orders.$orderId'
import { Route as AuthenticatedSalesOrdersNewRouteImport } from './routes/_authenticated/sales-orders.new'
import { Route as AuthenticatedSalesReturnsIndexRouteImport } from './routes/_authenticated/sales-returns.index'
import { Route as AuthenticatedSalesReturnsReturnIdRouteImport } from './routes/_authenticated/sales-returns.$returnId'
import { Route as AuthenticatedSalesReturnsNewRouteImport } from './routes/_authenticated/sales-returns.new'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors.index'
import { Route as AuthenticatedVendorsVendorIdRouteImport } from './routes/_authenticated/vendors.$vendorId'
import { Route as AuthenticatedWarehousesIndexRouteImport } from './routes/_authenticated/warehouses.index'
import { Route as AuthenticatedWarehousesWarehouseIdRouteImport } from './routes/_authenticated/warehouses.$warehouseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChequesRoute = AuthenticatedChequesRouteImport.update({
  id: '/cheques',
  path: '/cheques',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewBillRoute = AuthenticatedNewBillRouteImport.update({
  id: '/new-bill',
  path: '/new-bill',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsAccountIdRoute =
  AuthenticatedAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashBankIndexRoute =
  AuthenticatedCashBankIndexRouteImport.update({
    id: '/cash-bank/',
    path: '/cash-bank/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreditNotesIndexRoute =
  AuthenticatedCreditNotesIndexRouteImport.update({
    id: '/credit-notes/',
    path: '/credit-notes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreditNotesCreditNoteIdRoute =
  AuthenticatedCreditNotesCreditNoteIdRouteImport.update({
    id: '/credit-notes/$creditNoteId',
    path: '/credit-notes/$creditNoteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreditNotesNewRoute =
  AuthenticatedCreditNotesNewRouteImport.update({
    id: '/credit-notes/new',
    path: '/credit-notes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryNotesIndexRoute =
  AuthenticatedDeliveryNotesIndexRouteImport.update({
    id: '/delivery-notes/',
    path: '/delivery-notes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryNotesDeliveryIdRoute =
  AuthenticatedDeliveryNotesDeliveryIdRouteImport.update({
    id: '/delivery-notes/$deliveryId',
    path: '/delivery-notes/$deliveryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryNotesNewRoute =
  AuthenticatedDeliveryNotesNewRouteImport.update({
    id: '/delivery-notes/new',
    path: '/delivery-notes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseBillsIndexRoute =
  AuthenticatedPurchaseBillsIndexRouteImport.update({
    id: '/purchase-bills/',
    path: '/purchase-bills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseBillsPurchaseBillIdRoute =
  AuthenticatedPurchaseBillsPurchaseBillIdRouteImport.update({
    id: '/purchase-bills/$purchaseBillId',
    path: '/purchase-bills/$purchaseBillId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseBillsNewRoute =
  AuthenticatedPurchaseBillsNewRouteImport.update({
    id: '/purchase-bills/new',
    path: '/purchase-bills/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersOrderIdRoute =
  AuthenticatedPurchaseOrdersOrderIdRouteImport.update({
    id: '/purchase-orders/$orderId',
    path: '/purchase-orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersNewRoute =
  AuthenticatedPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders/new',
    path: '/purchase-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDayBookRoute =
  AuthenticatedReportsDayBookRouteImport.update({
    id: '/reports/day-book',
    path: '/reports/day-book',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPurchasesRoute =
  AuthenticatedReportsPurchasesRouteImport.update({
    id: '/reports/purchases',
    path: '/reports/purchases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/reports/sales',
    path: '/reports/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsTransactionsRoute =
  AuthenticatedReportsTransactionsRouteImport.update({
    id: '/reports/transactions',
    path: '/reports/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersIndexRoute =
  AuthenticatedSalesOrdersIndexRouteImport.update({
    id: '/sales-orders/',
    path: '/sales-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersOrderIdRoute =
  AuthenticatedSalesOrdersOrderIdRouteImport.update({
    id: '/sales-orders/$orderId',
    path: '/sales-orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersNewRoute =
  AuthenticatedSalesOrdersNewRouteImport.update({
    id: '/sales-orders/new',
    path: '/sales-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesReturnsIndexRoute =
  AuthenticatedSalesReturnsIndexRouteImport.update({
    id: '/sales-returns/',
    path: '/sales-returns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesReturnsReturnIdRoute =
  AuthenticatedSalesReturnsReturnIdRouteImport.update({
    id: '/sales-returns/$returnId',
    path: '/sales-returns/$returnId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesReturnsNewRoute =
  AuthenticatedSalesReturnsNewRouteImport.update({
    id: '/sales-returns/new',
    path: '/sales-returns/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsVendorIdRoute =
  AuthenticatedVendorsVendorIdRouteImport.update({
    id: '/vendors/$vendorId',
    path: '/vendors/$vendorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWarehousesIndexRoute =
  AuthenticatedWarehousesIndexRouteImport.update({
    id: '/warehouses/',
    path: '/warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWarehousesWarehouseIdRoute =
  AuthenticatedWarehousesWarehouseIdRouteImport.update({
    id: '/warehouses/$warehouseId',
    path: '/warehouses/$warehouseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cheques': typeof AuthenticatedChequesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-bill': typeof AuthenticatedNewBillRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/credit-notes/$creditNoteId': typeof AuthenticatedCreditNotesCreditNoteIdRoute
  '/credit-notes/new': typeof AuthenticatedCreditNotesNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery-notes/$deliveryId': typeof AuthenticatedDeliveryNotesDeliveryIdRoute
  '/delivery-notes/new': typeof AuthenticatedDeliveryNotesNewRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/purchase-bills/$purchaseBillId': typeof AuthenticatedPurchaseBillsPurchaseBillIdRoute
  '/purchase-bills/new': typeof AuthenticatedPurchaseBillsNewRoute
  '/purchase-orders/$orderId': typeof AuthenticatedPurchaseOrdersOrderIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/reports/day-book': typeof AuthenticatedReportsDayBookRoute
  '/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/reports/transactions': typeof AuthenticatedReportsTransactionsRoute
  '/sales-orders/$orderId': typeof AuthenticatedSalesOrdersOrderIdRoute
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/sales-returns/$returnId': typeof AuthenticatedSalesReturnsReturnIdRoute
  '/sales-returns/new': typeof AuthenticatedSalesReturnsNewRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/warehouses/$warehouseId': typeof AuthenticatedWarehousesWarehouseIdRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/cash-bank/': typeof AuthenticatedCashBankIndexRoute
  '/credit-notes/': typeof AuthenticatedCreditNotesIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/delivery-notes/': typeof AuthenticatedDeliveryNotesIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/purchase-bills/': typeof AuthenticatedPurchaseBillsIndexRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/sales-orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/sales-returns/': typeof AuthenticatedSalesReturnsIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/warehouses/': typeof AuthenticatedWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cheques': typeof AuthenticatedChequesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-bill': typeof AuthenticatedNewBillRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/credit-notes/$creditNoteId': typeof AuthenticatedCreditNotesCreditNoteIdRoute
  '/credit-notes/new': typeof AuthenticatedCreditNotesNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery-notes/$deliveryId': typeof AuthenticatedDeliveryNotesDeliveryIdRoute
  '/delivery-notes/new': typeof AuthenticatedDeliveryNotesNewRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/purchase-bills/$purchaseBillId': typeof AuthenticatedPurchaseBillsPurchaseBillIdRoute
  '/purchase-bills/new': typeof AuthenticatedPurchaseBillsNewRoute
  '/purchase-orders/$orderId': typeof AuthenticatedPurchaseOrdersOrderIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/reports/day-book': typeof AuthenticatedReportsDayBookRoute
  '/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/reports/transactions': typeof AuthenticatedReportsTransactionsRoute
  '/sales-orders/$orderId': typeof AuthenticatedSalesOrdersOrderIdRoute
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/sales-returns/$returnId': typeof AuthenticatedSalesReturnsReturnIdRoute
  '/sales-returns/new': typeof AuthenticatedSalesReturnsNewRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/warehouses/$warehouseId': typeof AuthenticatedWarehousesWarehouseIdRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/cash-bank': typeof AuthenticatedCashBankIndexRoute
  '/credit-notes': typeof AuthenticatedCreditNotesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/delivery-notes': typeof AuthenticatedDeliveryNotesIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/purchase-bills': typeof AuthenticatedPurchaseBillsIndexRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersIndexRoute
  '/sales-returns': typeof AuthenticatedSalesReturnsIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/warehouses': typeof AuthenticatedWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/cheques': typeof AuthenticatedChequesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new-bill': typeof AuthenticatedNewBillRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/credit-notes/$creditNoteId': typeof AuthenticatedCreditNotesCreditNoteIdRoute
  '/_authenticated/credit-notes/new': typeof AuthenticatedCreditNotesNewRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/delivery-notes/$deliveryId': typeof AuthenticatedDeliveryNotesDeliveryIdRoute
  '/_authenticated/delivery-notes/new': typeof AuthenticatedDeliveryNotesNewRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/purchase-bills/$purchaseBillId': typeof AuthenticatedPurchaseBillsPurchaseBillIdRoute
  '/_authenticated/purchase-bills/new': typeof AuthenticatedPurchaseBillsNewRoute
  '/_authenticated/purchase-orders/$orderId': typeof AuthenticatedPurchaseOrdersOrderIdRoute
  '/_authenticated/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/_authenticated/reports/day-book': typeof AuthenticatedReportsDayBookRoute
  '/_authenticated/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/reports/transactions': typeof AuthenticatedReportsTransactionsRoute
  '/_authenticated/sales-orders/$orderId': typeof AuthenticatedSalesOrdersOrderIdRoute
  '/_authenticated/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/_authenticated/sales-returns/$returnId': typeof AuthenticatedSalesReturnsReturnIdRoute
  '/_authenticated/sales-returns/new': typeof AuthenticatedSalesReturnsNewRoute
  '/_authenticated/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/_authenticated/warehouses/$warehouseId': typeof AuthenticatedWarehousesWarehouseIdRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/cash-bank/': typeof AuthenticatedCashBankIndexRoute
  '/_authenticated/credit-notes/': typeof AuthenticatedCreditNotesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/delivery-notes/': typeof AuthenticatedDeliveryNotesIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/purchase-bills/': typeof AuthenticatedPurchaseBillsIndexRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/sales-orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/_authenticated/sales-returns/': typeof AuthenticatedSalesReturnsIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/warehouses/': typeof AuthenticatedWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cheques'
    | '/dashboard'
    | '/new-bill'
    | '/settings'
    | '/accounts/$accountId'
    | '/bills/$billId'
    | '/credit-notes/$creditNoteId'
    | '/credit-notes/new'
    | '/customers/$customerId'
    | '/delivery-notes/$deliveryId'
    | '/delivery-notes/new'
    | '/products/$productId'
    | '/purchase-bills/$purchaseBillId'
    | '/purchase-bills/new'
    | '/purchase-orders/$orderId'
    | '/purchase-orders/new'
    | '/reports/day-book'
    | '/reports/purchases'
    | '/reports/sales'
    | '/reports/transactions'
    | '/sales-orders/$orderId'
    | '/sales-orders/new'
    | '/sales-returns/$returnId'
    | '/sales-returns/new'
    | '/vendors/$vendorId'
    | '/warehouses/$warehouseId'
    | '/accounts/'
    | '/bills/'
    | '/cash-bank/'
    | '/credit-notes/'
    | '/customers/'
    | '/delivery-notes/'
    | '/payments/'
    | '/products/'
    | '/purchase-bills/'
    | '/purchase-orders/'
    | '/reports/'
    | '/sales-orders/'
    | '/sales-returns/'
    | '/vendors/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cheques'
    | '/dashboard'
    | '/new-bill'
    | '/settings'
    | '/accounts/$accountId'
    | '/bills/$billId'
    | '/credit-notes/$creditNoteId'
    | '/credit-notes/new'
    | '/customers/$customerId'
    | '/delivery-notes/$deliveryId'
    | '/delivery-notes/new'
    | '/products/$productId'
    | '/purchase-bills/$purchaseBillId'
    | '/purchase-bills/new'
    | '/purchase-orders/$orderId'
    | '/purchase-orders/new'
    | '/reports/day-book'
    | '/reports/purchases'
    | '/reports/sales'
    | '/reports/transactions'
    | '/sales-orders/$orderId'
    | '/sales-orders/new'
    | '/sales-returns/$returnId'
    | '/sales-returns/new'
    | '/vendors/$vendorId'
    | '/warehouses/$warehouseId'
    | '/accounts'
    | '/bills'
    | '/cash-bank'
    | '/credit-notes'
    | '/customers'
    | '/delivery-notes'
    | '/payments'
    | '/products'
    | '/purchase-bills'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/sales-returns'
    | '/vendors'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/cheques'
    | '/_authenticated/dashboard'
    | '/_authenticated/new-bill'
    | '/_authenticated/settings'
    | '/_authenticated/accounts/$accountId'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/credit-notes/$creditNoteId'
    | '/_authenticated/credit-notes/new'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/delivery-notes/$deliveryId'
    | '/_authenticated/delivery-notes/new'
    | '/_authenticated/products/$productId'
    | '/_authenticated/purchase-bills/$purchaseBillId'
    | '/_authenticated/purchase-bills/new'
    | '/_authenticated/purchase-orders/$orderId'
    | '/_authenticated/purchase-orders/new'
    | '/_authenticated/reports/day-book'
    | '/_authenticated/reports/purchases'
    | '/_authenticated/reports/sales'
    | '/_authenticated/reports/transactions'
    | '/_authenticated/sales-orders/$orderId'
    | '/_authenticated/sales-orders/new'
    | '/_authenticated/sales-returns/$returnId'
    | '/_authenticated/sales-returns/new'
    | '/_authenticated/vendors/$vendorId'
    | '/_authenticated/warehouses/$warehouseId'
    | '/_authenticated/accounts/'
    | '/_authenticated/bills/'
    | '/_authenticated/cash-bank/'
    | '/_authenticated/credit-notes/'
    | '/_authenticated/customers/'
    | '/_authenticated/delivery-notes/'
    | '/_authenticated/payments/'
    | '/_authenticated/products/'
    | '/_authenticated/purchase-bills/'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/reports/'
    | '/_authenticated/sales-orders/'
    | '/_authenticated/sales-returns/'
    | '/_authenticated/vendors/'
    | '/_authenticated/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cheques': {
      id: '/_authenticated/cheques'
      path: '/cheques'
      fullPath: '/cheques'
      preLoaderRoute: typeof AuthenticatedChequesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-bill': {
      id: '/_authenticated/new-bill'
      path: '/new-bill'
      fullPath: '/new-bill'
      preLoaderRoute: typeof AuthenticatedNewBillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$accountId': {
      id: '/_authenticated/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-bank/': {
      id: '/_authenticated/cash-bank/'
      path: '/cash-bank'
      fullPath: '/cash-bank/'
      preLoaderRoute: typeof AuthenticatedCashBankIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-notes/': {
      id: '/_authenticated/credit-notes/'
      path: '/credit-notes'
      fullPath: '/credit-notes/'
      preLoaderRoute: typeof AuthenticatedCreditNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-notes/$creditNoteId': {
      id: '/_authenticated/credit-notes/$creditNoteId'
      path: '/credit-notes/$creditNoteId'
      fullPath: '/credit-notes/$creditNoteId'
      preLoaderRoute: typeof AuthenticatedCreditNotesCreditNoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-notes/new': {
      id: '/_authenticated/credit-notes/new'
      path: '/credit-notes/new'
      fullPath: '/credit-notes/new'
      preLoaderRoute: typeof AuthenticatedCreditNotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-notes/': {
      id: '/_authenticated/delivery-notes/'
      path: '/delivery-notes'
      fullPath: '/delivery-notes/'
      preLoaderRoute: typeof AuthenticatedDeliveryNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-notes/$deliveryId': {
      id: '/_authenticated/delivery-notes/$deliveryId'
      path: '/delivery-notes/$deliveryId'
      fullPath: '/delivery-notes/$deliveryId'
      preLoaderRoute: typeof AuthenticatedDeliveryNotesDeliveryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-notes/new': {
      id: '/_authenticated/delivery-notes/new'
      path: '/delivery-notes/new'
      fullPath: '/delivery-notes/new'
      preLoaderRoute: typeof AuthenticatedDeliveryNotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-bills/': {
      id: '/_authenticated/purchase-bills/'
      path: '/purchase-bills'
      fullPath: '/purchase-bills/'
      preLoaderRoute: typeof AuthenticatedPurchaseBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-bills/$purchaseBillId': {
      id: '/_authenticated/purchase-bills/$purchaseBillId'
      path: '/purchase-bills/$purchaseBillId'
      fullPath: '/purchase-bills/$purchaseBillId'
      preLoaderRoute: typeof AuthenticatedPurchaseBillsPurchaseBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-bills/new': {
      id: '/_authenticated/purchase-bills/new'
      path: '/purchase-bills/new'
      fullPath: '/purchase-bills/new'
      preLoaderRoute: typeof AuthenticatedPurchaseBillsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/$orderId': {
      id: '/_authenticated/purchase-orders/$orderId'
      path: '/purchase-orders/$orderId'
      fullPath: '/purchase-orders/$orderId'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/new': {
      id: '/_authenticated/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/day-book': {
      id: '/_authenticated/reports/day-book'
      path: '/reports/day-book'
      fullPath: '/reports/day-book'
      preLoaderRoute: typeof AuthenticatedReportsDayBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/purchases': {
      id: '/_authenticated/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AuthenticatedReportsPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/transactions': {
      id: '/_authenticated/reports/transactions'
      path: '/reports/transactions'
      fullPath: '/reports/transactions'
      preLoaderRoute: typeof AuthenticatedReportsTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders/': {
      id: '/_authenticated/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders/$orderId': {
      id: '/_authenticated/sales-orders/$orderId'
      path: '/sales-orders/$orderId'
      fullPath: '/sales-orders/$orderId'
      preLoaderRoute: typeof AuthenticatedSalesOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders/new': {
      id: '/_authenticated/sales-orders/new'
      path: '/sales-orders/new'
      fullPath: '/sales-orders/new'
      preLoaderRoute: typeof AuthenticatedSalesOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-returns/': {
      id: '/_authenticated/sales-returns/'
      path: '/sales-returns'
      fullPath: '/sales-returns/'
      preLoaderRoute: typeof AuthenticatedSalesReturnsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-returns/$returnId': {
      id: '/_authenticated/sales-returns/$returnId'
      path: '/sales-returns/$returnId'
      fullPath: '/sales-returns/$returnId'
      preLoaderRoute: typeof AuthenticatedSalesReturnsReturnIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-returns/new': {
      id: '/_authenticated/sales-returns/new'
      path: '/sales-returns/new'
      fullPath: '/sales-returns/new'
      preLoaderRoute: typeof AuthenticatedSalesReturnsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$vendorId': {
      id: '/_authenticated/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof AuthenticatedVendorsVendorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses/': {
      id: '/_authenticated/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AuthenticatedWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses/$warehouseId': {
      id: '/_authenticated/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof AuthenticatedWarehousesWarehouseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChequesRoute: typeof AuthenticatedChequesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewBillRoute: typeof AuthenticatedNewBillRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAccountsAccountIdRoute: typeof AuthenticatedAccountsAccountIdRoute
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedCreditNotesCreditNoteIdRoute: typeof AuthenticatedCreditNotesCreditNoteIdRoute
  AuthenticatedCreditNotesNewRoute: typeof AuthenticatedCreditNotesNewRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedDeliveryNotesDeliveryIdRoute: typeof AuthenticatedDeliveryNotesDeliveryIdRoute
  AuthenticatedDeliveryNotesNewRoute: typeof AuthenticatedDeliveryNotesNewRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedPurchaseBillsPurchaseBillIdRoute: typeof AuthenticatedPurchaseBillsPurchaseBillIdRoute
  AuthenticatedPurchaseBillsNewRoute: typeof AuthenticatedPurchaseBillsNewRoute
  AuthenticatedPurchaseOrdersOrderIdRoute: typeof AuthenticatedPurchaseOrdersOrderIdRoute
  AuthenticatedPurchaseOrdersNewRoute: typeof AuthenticatedPurchaseOrdersNewRoute
  AuthenticatedReportsDayBookRoute: typeof AuthenticatedReportsDayBookRoute
  AuthenticatedReportsPurchasesRoute: typeof AuthenticatedReportsPurchasesRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedReportsTransactionsRoute: typeof AuthenticatedReportsTransactionsRoute
  AuthenticatedSalesOrdersOrderIdRoute: typeof AuthenticatedSalesOrdersOrderIdRoute
  AuthenticatedSalesOrdersNewRoute: typeof AuthenticatedSalesOrdersNewRoute
  AuthenticatedSalesReturnsReturnIdRoute: typeof AuthenticatedSalesReturnsReturnIdRoute
  AuthenticatedSalesReturnsNewRoute: typeof AuthenticatedSalesReturnsNewRoute
  AuthenticatedVendorsVendorIdRoute: typeof AuthenticatedVendorsVendorIdRoute
  AuthenticatedWarehousesWarehouseIdRoute: typeof AuthenticatedWarehousesWarehouseIdRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedCashBankIndexRoute: typeof AuthenticatedCashBankIndexRoute
  AuthenticatedCreditNotesIndexRoute: typeof AuthenticatedCreditNotesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDeliveryNotesIndexRoute: typeof AuthenticatedDeliveryNotesIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedPurchaseBillsIndexRoute: typeof AuthenticatedPurchaseBillsIndexRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSalesOrdersIndexRoute: typeof AuthenticatedSalesOrdersIndexRoute
  AuthenticatedSalesReturnsIndexRoute: typeof AuthenticatedSalesReturnsIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedWarehousesIndexRoute: typeof AuthenticatedWarehousesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChequesRoute: AuthenticatedChequesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewBillRoute: AuthenticatedNewBillRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAccountsAccountIdRoute: AuthenticatedAccountsAccountIdRoute,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedCreditNotesCreditNoteIdRoute:
    AuthenticatedCreditNotesCreditNoteIdRoute,
  AuthenticatedCreditNotesNewRoute: AuthenticatedCreditNotesNewRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedDeliveryNotesDeliveryIdRoute:
    AuthenticatedDeliveryNotesDeliveryIdRoute,
  AuthenticatedDeliveryNotesNewRoute: AuthenticatedDeliveryNotesNewRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedPurchaseBillsPurchaseBillIdRoute:
    AuthenticatedPurchaseBillsPurchaseBillIdRoute,
  AuthenticatedPurchaseBillsNewRoute: AuthenticatedPurchaseBillsNewRoute,
  AuthenticatedPurchaseOrdersOrderIdRoute:
    AuthenticatedPurchaseOrdersOrderIdRoute,
  AuthenticatedPurchaseOrdersNewRoute: AuthenticatedPurchaseOrdersNewRoute,
  AuthenticatedReportsDayBookRoute: AuthenticatedReportsDayBookRoute,
  AuthenticatedReportsPurchasesRoute: AuthenticatedReportsPurchasesRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedReportsTransactionsRoute: AuthenticatedReportsTransactionsRoute,
  AuthenticatedSalesOrdersOrderIdRoute: AuthenticatedSalesOrdersOrderIdRoute,
  AuthenticatedSalesOrdersNewRoute: AuthenticatedSalesOrdersNewRoute,
  AuthenticatedSalesReturnsReturnIdRoute:
    AuthenticatedSalesReturnsReturnIdRoute,
  AuthenticatedSalesReturnsNewRoute: AuthenticatedSalesReturnsNewRoute,
  AuthenticatedVendorsVendorIdRoute: AuthenticatedVendorsVendorIdRoute,
  AuthenticatedWarehousesWarehouseIdRoute:
    AuthenticatedWarehousesWarehouseIdRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedCashBankIndexRoute: AuthenticatedCashBankIndexRoute,
  AuthenticatedCreditNotesIndexRoute: AuthenticatedCreditNotesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDeliveryNotesIndexRoute: AuthenticatedDeliveryNotesIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedPurchaseBillsIndexRoute: AuthenticatedPurchaseBillsIndexRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSalesOrdersIndexRoute: AuthenticatedSalesOrdersIndexRoute,
  AuthenticatedSalesReturnsIndexRoute: AuthenticatedSalesReturnsIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedWarehousesIndexRoute: AuthenticatedWarehousesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
