/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNewBillRouteImport } from './routes/_authenticated/new-bill'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills.index'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills.$billId'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedWarehousesIndexRouteImport } from './routes/_authenticated/warehouses.index'
import { Route as AuthenticatedWarehousesWarehouseIdRouteImport } from './routes/_authenticated/warehouses.$warehouseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewBillRoute = AuthenticatedNewBillRouteImport.update({
  id: '/new-bill',
  path: '/new-bill',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWarehousesIndexRoute =
  AuthenticatedWarehousesIndexRouteImport.update({
    id: '/warehouses/',
    path: '/warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWarehousesWarehouseIdRoute =
  AuthenticatedWarehousesWarehouseIdRouteImport.update({
    id: '/warehouses/$warehouseId',
    path: '/warehouses/$warehouseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-bill': typeof AuthenticatedNewBillRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/warehouses/$warehouseId': typeof AuthenticatedWarehousesWarehouseIdRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/warehouses/': typeof AuthenticatedWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-bill': typeof AuthenticatedNewBillRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/warehouses/$warehouseId': typeof AuthenticatedWarehousesWarehouseIdRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/warehouses': typeof AuthenticatedWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new-bill': typeof AuthenticatedNewBillRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/warehouses/$warehouseId': typeof AuthenticatedWarehousesWarehouseIdRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/warehouses/': typeof AuthenticatedWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/new-bill'
    | '/settings'
    | '/bills/$billId'
    | '/customers/$customerId'
    | '/products/$productId'
    | '/warehouses/$warehouseId'
    | '/bills/'
    | '/customers/'
    | '/products/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/new-bill'
    | '/settings'
    | '/bills/$billId'
    | '/customers/$customerId'
    | '/products/$productId'
    | '/warehouses/$warehouseId'
    | '/bills'
    | '/customers'
    | '/products'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/new-bill'
    | '/_authenticated/settings'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/products/$productId'
    | '/_authenticated/warehouses/$warehouseId'
    | '/_authenticated/bills/'
    | '/_authenticated/customers/'
    | '/_authenticated/products/'
    | '/_authenticated/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-bill': {
      id: '/_authenticated/new-bill'
      path: '/new-bill'
      fullPath: '/new-bill'
      preLoaderRoute: typeof AuthenticatedNewBillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses/': {
      id: '/_authenticated/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AuthenticatedWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses/$warehouseId': {
      id: '/_authenticated/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof AuthenticatedWarehousesWarehouseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewBillRoute: typeof AuthenticatedNewBillRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedWarehousesWarehouseIdRoute: typeof AuthenticatedWarehousesWarehouseIdRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedWarehousesIndexRoute: typeof AuthenticatedWarehousesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewBillRoute: AuthenticatedNewBillRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedWarehousesWarehouseIdRoute:
    AuthenticatedWarehousesWarehouseIdRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedWarehousesIndexRoute: AuthenticatedWarehousesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
